name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    services:
      # mysql-service Label used to access the service container
      mysql-service:
        # Docker Hub image (also with version)
        image: mysql:8.0
        env:
          ## Accessing to Github secrets, where you can store your configuration
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: test
        ## map the "external" 33306 port with the "internal" 3306
        ports:
          - 33306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.2"]
        ghc: ["8.6.5", "8.8.3", "8.10.1"]
    env:
      CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1.2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Check MySQL connection
        run: mysql -utest -ptest -h127.0.0.1 --port=33306 test -e "SELECT 1;"
      - uses: harmon758/postgresql-action@v1
        with:
           postgresql version: '12'  # See https://hub.docker.com/_/postgres for available versions  
           postgresql user: postgres
           postgresql db: test
           # - uses: mirromutth/mysql-action@v1.1
           #   with:
           #     mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
           #     mysql database: 'test' # Optional, default value is "test". The specified database which will be create
           #     mysql user: 'test' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
           #     mysql password: 'test' # Required if "mysql user" exists. The password for the "mysql user"
      - run: cabal v2-update
      - run: cabal v2-freeze $CONFIG
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal v2-build all $CONFIG
      - run: cabal v2-test all $CONFIG
      - run: cabal v2-haddock all $CONFIG
      - run: cabal v2-sdist all
